version: '3'
services:
  app:
    container_name: flutter_notifications
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      - NODE_ENV=development
