version: '3'
services:
  app:
    container_name: flutter_notifications
    build: .
    ports:
      - "3000:3000" 
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    restart: unless-stopped
